const traza = {
  codigo_ant: "CNI-3-WMHJEM",
  codigo_de_la_parcela: "WJM 3",
  razon_social: "WALTER MARICHI HUANUIRI/ JUAN ELVER MARICHI",
  dni_ruc: "04807157",
  edad: 62,
  sector: "CN. INFIERNO",
  distrito: "Tambopata",
  provincia: "Tambopata",
  departamento: "Madre de Dios",
  nombre_del_area_castanera: "Tres Chimbadas ",
  nro_de_contrato: "RGR-N 019-2020-GOREMAD-GRFFS",
  nombre_cientifico: "Bertholletia Excelsa",
  nro_de_arbol: 3,
  nro_de_estrada: 1,
  dap: "2.36",
  ht: "38.00",
  este: "466409",
  norte: "8587635",
  productivo: "Si",
  semillero: "No",
  produccion_latas: "3.00",
  juvenil_o_maduro: "Maduro",
  sano_o_enfermo: "Enfermo",
  rama_caida: "Si",
  lianas: "Si",
  cerca_a_area_deforestada: "No",
  dentro_de_area_deforestada: "No",
  cerca_a_carretera: "No",
  en_estrada: "Si",
  campamento: "No",
  banho: "No",
  realiza_quemas: "No",
  combustible_para_transporte: "Si",
  nro_celular: "974344581",
  observaciones: "",
};

const data2 = {
  parcela: {
    codigo_de_la_parcela: traza.codigo_de_la_parcela,
    ubicacion: {
      sector: traza.sector,
      distrito: traza.distrito,
      provincia: traza.provincia,
      departamento: traza.departamento,
    },
    nombre_del_area_castanera: traza.nombre_del_area_castanera,
    nro_de_contrato: traza.nro_de_contrato,
  },
  comunero: {
    dni_ruc: traza.dni_ruc,
    edad: traza.edad,
    razon_social: traza.razon_social,
    nro_celular: traza.nro_celular,
  },
  arbol: {
    codigo_ant: traza.codigo_ant,
    nombre_cientifico: traza.nombre_cientifico,
    nro_de_arbol: traza.nro_de_arbol,
    nro_de_estrada: traza.nro_de_estrada,
    parametros_dasometricos: {
      dap: traza.dap,
      ht: traza.ht,
    },
    coordenadas_utm: {
      este: traza.este,
      norte: traza.norte,
    },
    condicion_arbol: {
      productivo: traza.productivo,
      semillero: traza.semillero,
    },
    produccion_latas: traza.produccion_latas,
    condicion_arbol: {
      juvenil_o_maduro: traza.juvenil_o_maduro,
      sano_o_enfermo: traza.sano_o_enfermo,
      rama_caida: traza.rama_caida,
      lianas: traza.lianas,
    },
    ubicacion_a_un_area_deforestada: {
      cerca_a_area_deforestada: traza.cerca_a_area_deforestada,
      dentro_de_area_deforestada: traza.dentro_de_area_deforestada,
      cerca_a_carretera: traza.cerca_a_carretera,
      en_estrada: traza.en_estrada,
    },
  },
  informacion_complementaria: {
    campamento: traza.campamento,
    banho: traza.banho,
    realiza_quemas: traza.realiza_quemas,
    combustible_para_transporte: traza.combustible_para_transporte,
  },
  observaciones: traza.observaciones,
};

console.log(data2)